<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tianrui Xie">
<meta name="dcterms.date" content="2025-03-18">

<title>Group_14_Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Group_Analysis_English_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group_Analysis_English_files/libs/quarto-html/quarto.js"></script>
<script src="Group_Analysis_English_files/libs/quarto-html/popper.min.js"></script>
<script src="Group_Analysis_English_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Group_Analysis_English_files/libs/quarto-html/anchor.min.js"></script>
<link href="Group_Analysis_English_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group_Analysis_English_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Group_Analysis_English_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Group_Analysis_English_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Group_Analysis_English_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Group_14_Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tianrui Xie </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 18, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="data-analysis-report" class="level1">
<h1>Data Analysis Report</h1>
<section id="data-loading" class="level2">
<h2 class="anchored" data-anchor-id="data-loading"><strong>1.</strong> Data Loading</h2>
<p>In this project, we used <code>dataset14.csv</code>, which contains coffee quality ratings as well as some chemical characteristics such as <code>aroma</code>, <code>flavor</code>, and <code>acidity</code>.</p>
<p>First, we load the data and examine its structure, including:</p>
<ul>
<li>The types of variables (numerical, categorical)</li>
<li>Missing values</li>
<li>Basic statistical information of variables (mean, median, standard deviation, etc.)</li>
</ul>
<p>This helps us understand the fundamental characteristics of the data, preparing for subsequent data cleaning and analysis.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1134 obs. of  8 variables:
 $ country_of_origin   : chr  "China" "Mexico" "Brazil" "United States (Hawaii)" ...
 $ aroma               : num  7.25 7.58 8.25 7.92 7.42 7.67 7.42 7.42 7.67 7.25 ...
 $ flavor              : num  7.08 7.08 7.83 7.92 7.33 7.83 7.5 7.58 7.67 7.08 ...
 $ acidity             : num  7.17 7.58 8.33 7.92 7.58 7.92 7.42 7.17 7.67 7.33 ...
 $ category_two_defects: int  14 4 0 6 0 7 10 0 4 45 ...
 $ altitude_mean_meters: num  1700 1022 1268 NA NA ...
 $ harvested           : int  2013 2013 2016 2012 2013 2015 2015 NA 2014 2012 ...
 $ Qualityclass        : chr  "Poor" "Poor" "Poor" "Good" ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> country_of_origin      aroma           flavor         acidity     
 Length:1134        Min.   :0.000   Min.   :0.000   Min.   :0.000  
 Class :character   1st Qu.:7.420   1st Qu.:7.330   1st Qu.:7.330  
 Mode  :character   Median :7.580   Median :7.580   Median :7.580  
                    Mean   :7.568   Mean   :7.523   Mean   :7.538  
                    3rd Qu.:7.750   3rd Qu.:7.750   3rd Qu.:7.750  
                    Max.   :8.750   Max.   :8.830   Max.   :8.750  
                                                                   
 category_two_defects altitude_mean_meters   harvested    Qualityclass      
 Min.   : 0.000       Min.   :     1       Min.   :2010   Length:1134       
 1st Qu.: 0.000       1st Qu.:  1100       1st Qu.:2012   Class :character  
 Median : 2.000       Median :  1311       Median :2014   Mode  :character  
 Mean   : 3.501       Mean   :  1653       Mean   :2014                     
 3rd Qu.: 4.000       3rd Qu.:  1600       3rd Qu.:2015                     
 Max.   :55.000       Max.   :190164       Max.   :2018                     
                      NA's   :199          NA's   :59                       </code></pre>
</div>
</div>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning"><strong>2.</strong> Data Cleaning</h2>
<p>During the data cleaning process, we performed the following operations:</p>
<section id="handling-missing-values" class="level3">
<h3 class="anchored" data-anchor-id="handling-missing-values">Handling Missing Values:</h3>
<ul>
<li><strong><code>country_of_origin</code> (Coffee Origin):</strong> Few missing values, so we directly removed the corresponding rows.</li>
<li><strong><code>altitude_mean_meters</code> (Altitude):</strong> Filled missing values with the median, as altitude data might have a skewed distribution.</li>
<li><strong><code>harvested</code> (Harvest Year):</strong> Filled missing values with the mode, as the year is a discrete variable, making the mode the most reasonable imputation method.</li>
</ul>
</section>
<section id="handling-outliers" class="level3">
<h3 class="anchored" data-anchor-id="handling-outliers">Handling Outliers:</h3>
<ul>
<li><strong><code>altitude_mean_meters</code>:</strong> The maximum value was found to be 190,164m, which is clearly abnormal. Therefore, we removed observations above 5,000m.</li>
</ul>
</section>
<section id="variable-transformation" class="level3">
<h3 class="anchored" data-anchor-id="variable-transformation">Variable Transformation:</h3>
<ul>
<li><strong><code>category_two_defects</code> (Number of Secondary Defects):</strong> Highly right-skewed, so we applied a log transformation (<code>log+1</code>) to reduce the influence of extreme values.</li>
<li><strong><code>Qualityclass</code> (Quality Grade):</strong> A categorical variable that was binarized (<code>Good = 1</code>, <code>Poor = 0</code>) to facilitate logistic regression analysis.</li>
</ul>
<p>After data cleaning, the dataset has no missing values, major outliers have been removed, and the data quality is ensured to be reliable.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> country_of_origin      aroma           flavor         acidity     
 Length:1129        Min.   :5.080   Min.   :6.080   Min.   :5.250  
 Class :character   1st Qu.:7.420   1st Qu.:7.330   1st Qu.:7.330  
 Mode  :character   Median :7.580   Median :7.580   Median :7.580  
                    Mean   :7.576   Mean   :7.531   Mean   :7.545  
                    3rd Qu.:7.750   3rd Qu.:7.750   3rd Qu.:7.750  
                    Max.   :8.750   Max.   :8.830   Max.   :8.750  
 category_two_defects altitude_mean_meters   harvested    Qualityclass      
 Min.   : 0.000       Min.   :   1         Min.   :2010   Length:1129       
 1st Qu.: 0.000       1st Qu.:1200         1st Qu.:2012   Class :character  
 Median : 2.000       Median :1311         Median :2013   Mode  :character  
 Mean   : 3.492       Mean   :1322         Mean   :2014                     
 3rd Qu.: 4.000       3rd Qu.:1550         3rd Qu.:2015                     
 Max.   :55.000       Max.   :4287         Max.   :2018                     
 category_two_defects_log Qualityclass_binary
 Min.   :0.000            Min.   :0.0000     
 1st Qu.:0.000            1st Qu.:0.0000     
 Median :1.099            Median :1.0000     
 Mean   :1.084            Mean   :0.5146     
 3rd Qu.:1.609            3rd Qu.:1.0000     
 Max.   :4.025            Max.   :1.0000     </code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-eda"><strong>3.</strong> Exploratory Data Analysis (EDA)</h2>
<section id="data-distribution" class="level3">
<h3 class="anchored" data-anchor-id="data-distribution"><strong>3.1</strong> Data Distribution</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Analysis_English_files/figure-html/eda_plots-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>In the exploratory data analysis (EDA), we first examined the distribution of several key variables:</p>
<ul>
<li><strong><code>Aroma</code>:</strong> Mainly concentrated between 7.0 and 8.5, following a normal distribution.</li>
<li><strong><code>Flavor</code>:</strong> Similar to aroma, with most values above 7.0.</li>
<li><strong><code>Acidity</code>:</strong> Its distribution is close to that of aroma but slightly skewed.</li>
</ul>
<p>Overall, aroma, flavor, and acidity share similar distribution patterns, suggesting a potential strong correlation among them. This will be further confirmed in the subsequent correlation analysis.</p>
</section>
<section id="variable-correlation" class="level3">
<h3 class="anchored" data-anchor-id="variable-correlation"><strong>3.2</strong> Variable Correlation</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Analysis_English_files/figure-html/correlation_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We calculated the correlation among <strong><code>aroma</code></strong>, <strong><code>flavor</code></strong>, <strong><code>acidity</code></strong>, <strong><code>category_two_defects_log</code></strong>, and <strong><code>altitude_mean_meters</code></strong>, and visualized the results using a correlation heatmap.</p>
<ul>
<li><p><strong><code>Aroma</code></strong>, <strong><code>flavor</code></strong>, and <strong><code>acidity</code></strong> exhibit a strong correlation (0.6–0.8), indicating that they may have a similar impact on <strong><code>Qualityclass</code></strong>.</p></li>
<li><p><strong><code>Category_two_defects_log</code></strong> might be related to <strong><code>Qualityclass</code></strong>, but it shows a lower correlation with <strong><code>aroma and flavor</code></strong>.</p></li>
<li><p><strong><code>Altitude_mean_meters</code></strong> appears to have a minimal effect on <strong><code>Qualityclass</code></strong>.</p></li>
</ul>
<p>This analysis provides a foundation for our GLM modeling, where we will further examine the influence of these variables in the regression model.</p>
</section>
</section>
<section id="generalized-linear-model-glm" class="level2">
<h2 class="anchored" data-anchor-id="generalized-linear-model-glm"><strong>4. Generalized Linear Model (</strong>GLM)</h2>
<p>To predict the coffee quality grade (<strong><code>Qualityclass</code></strong>), we used a Generalized Linear Model (GLM), where:</p>
<ul>
<li><p><strong>Response Variable</strong>：<code>Qualityclass_binary</code>（<code>Good=1</code>，<code>Poor=0</code>）</p></li>
<li><p><strong>Predictor Variables</strong>：</p>
<ul>
<li><p><code>aroma</code></p></li>
<li><p><code>flavor</code></p></li>
<li><p><code>acidity</code></p></li>
<li><p><code>altitude_mean_meters</code></p></li>
<li><p><code>harvested</code></p></li>
<li><p><code>category_two_defects_log</code></p></li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Qualityclass_binary ~ aroma + flavor + acidity + 
    altitude_mean_meters + harvested + category_two_defects_log, 
    family = binomial, data = df)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -2.098e+02  1.066e+02  -1.969   0.0490 *  
aroma                     4.323e+00  5.922e-01   7.300 2.88e-13 ***
flavor                    7.424e+00  7.409e-01  10.020  &lt; 2e-16 ***
acidity                   3.246e+00  5.429e-01   5.978 2.26e-09 ***
altitude_mean_meters      4.299e-04  2.092e-04   2.055   0.0399 *  
harvested                 4.767e-02  5.267e-02   0.905   0.3654    
category_two_defects_log  6.155e-02  1.186e-01   0.519   0.6037    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1564.16  on 1128  degrees of freedom
Residual deviance:  675.48  on 1122  degrees of freedom
AIC: 689.48

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>The model equation is as follows:：</p>
<p><span class="math display">\[
\begin{aligned}
\log\left(\frac{P(\mathrm{Good})}{1-P(\mathrm{Good})}\right)=-209.8+4.32\cdot\mathrm{aroma}+7.42\cdot\mathrm{flavor}+3.25\cdot\mathrm{acidity}+0.0004299\cdot\\\mathrm{altitude\_mean\_meters}+0.0477\cdot\mathrm{harvested}+0.0616\cdot\mathrm{category\_two\_defects\_log}
\end{aligned}
\]</span></p>
</section>
<section id="variable-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="variable-interpretation">Variable Interpretation</h2>
<section id="key-influencing-factors" class="level3">
<h3 class="anchored" data-anchor-id="key-influencing-factors"><strong>1.</strong> Key Influencing Factors</h3>
<ul>
<li><p><strong><code>flavor</code></strong></p>
<ul>
<li><strong>Coefficient = 7.42</strong>, <strong>p &lt; 0.001</strong> (highly significant).</li>
<li>This indicates that for every 1-point increase in flavor score, the log-odds of the coffee being rated as “Good” increases by 7.42.</li>
<li>Flavor remains the most critical influencing factor.</li>
</ul></li>
<li><p><strong><code>aroma</code></strong></p>
<ul>
<li><strong>Coefficient = 4.32, p &lt; 0.001</strong> (highly significant).</li>
<li>A 1-point increase in aroma score significantly increases the probability of the coffee being rated as “Good”.</li>
</ul></li>
<li><p><strong><code>acidity</code></strong></p>
<ul>
<li><strong>Coefficient = 3.25, p &lt; 0.001</strong> (highly significant).</li>
<li>An increase in acidity enhances the coffee quality grade.</li>
</ul></li>
</ul>
</section>
<section id="factors-with-minor-or-insignificant-influence" class="level3">
<h3 class="anchored" data-anchor-id="factors-with-minor-or-insignificant-influence"><strong>2.</strong> Factors with Minor or Insignificant Influence</h3>
<ul>
<li><p><strong><code>altitude_mean_meters</code></strong></p>
<ul>
<li><strong>Coefficient = 0.0004299, p = 0.0399</strong> (significant).</li>
<li>Although the coefficient is small, it still suggests that higher altitude may have a <strong>positive impact</strong> on coffee quality.</li>
</ul></li>
<li><p><strong><code>harvested</code></strong></p>
<ul>
<li><p><strong>Coefficient = 0.0477, p = 0.3654</strong> (not significant).</p>
<p>The harvest year does not have a significant impact on coffee quality, indicating that the quality differences between different years are minimal.</p></li>
</ul></li>
<li><p><strong><code>category_two_defects_log</code></strong></p>
<ul>
<li><p><strong>Coefficient = 0.0616, p = 0.6037 (not significant).</strong></p></li>
<li><p>This suggests that the <strong>number of defects in coffee beans (category_two_defects_log)</strong> has a weak predictive ability for coffee quality.</p></li>
<li><p>Possible reasons include:</p>
<ul>
<li><p>Defect count may be <strong>highly correlated</strong> with variables like <strong>flavor</strong> and <strong>aroma</strong>.</p></li>
<li><p>There may be <strong>no significant distinction</strong> between “Good” and “Poor” coffee in terms of <strong>category_two_defects_log</strong>.</p></li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="model-refinement" class="level3">
<h3 class="anchored" data-anchor-id="model-refinement"><strong>Model Refinement:</strong></h3>
<p>We ultimately discard <code>altitude_mean_meters</code>, <code>harvested</code>, and <code>category_two_defects_log</code> and <strong>refit the model</strong>, obtaining a <strong>new refined model</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Qualityclass_binary ~ aroma + flavor + acidity, 
    family = binomial, data = df)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -113.0519     7.1776 -15.751  &lt; 2e-16 ***
aroma          4.3619     0.5929   7.357 1.88e-13 ***
flavor         7.2856     0.7313   9.963  &lt; 2e-16 ***
acidity        3.3281     0.5402   6.161 7.24e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1564.16  on 1128  degrees of freedom
Residual deviance:  680.53  on 1125  degrees of freedom
AIC: 688.53

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>At this point, the <strong>model equation</strong> is:</p>
<p><span class="math display">\[
\begin{aligned}
\log\left(\frac{P(\mathrm{Good})}{1-P(\mathrm{Good})}\right)=-113.1+4.36\cdot\mathrm{aroma}+7.28\cdot\mathrm{flavor}+3.32\cdot\mathrm{acidity}
\end{aligned}
\]</span></p>
</section>
</section>
<section id="model-evaluation" class="level2">
<h2 class="anchored" data-anchor-id="model-evaluation"><strong>5.</strong> Model Evaluation</h2>
<p>Calculate <strong>AUC-ROC</strong> and <strong>Confusion Matrix</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Accuracy: 0.87422497785651"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AUC-ROC: 0.944124778572057"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confusion Matrix:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   0   1
        0 472  66
        1  76 515</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Analysis_English_files/figure-html/model_evaluation-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<section id="aoc-snd-roc" class="level3">
<h3 class="anchored" data-anchor-id="aoc-snd-roc">1.AOC snd ROC</h3>
<ul>
<li><p><strong>AUC-ROC = 0.944</strong></p></li>
<li><p>The ROC curve is very close to the top-left corner, indicating that the model has <strong>strong discriminative power</strong>.</p></li>
<li><p>An <strong>AUC &gt; 0.9</strong> is generally considered an <strong>excellent classifier</strong>, meaning the model can effectively distinguish between different categories of data.</p>
<h4 id="conclusion" class="anchored"><strong>Conclusion</strong></h4>
<p>Your model performs <strong>exceptionally well</strong> in distinguishing between <strong>high-quality</strong> and <strong>low-quality</strong> coffee categories, with a <strong>low error rate</strong>.</p></li>
</ul>
</section>
<section id="confusion-matrix-analysis" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrix-analysis"><strong>2.Confusion Matrix Analysis</strong></h3>
<section id="actual-vs.-predicted-classes" class="level4">
<h4 class="anchored" data-anchor-id="actual-vs.-predicted-classes">Actual vs.&nbsp;Predicted Classes</h4>
<ul>
<li><p><strong>True Positives</strong> (TP, Predicted = 1, Actual = 1)<strong>:</strong> 515</p></li>
<li><p><strong>True Negatives</strong> (TN, Predicted = 0, Actual = 0): 472</p></li>
<li><p><strong>False Positives</strong> (FP, Predicted = 1, Actual = 0): 66</p></li>
<li><p><strong>False Negatives</strong> (FN, Predicted = 0, Actual = 1): 76</p></li>
</ul>
<p><strong>Accuracy = 87.42%</strong></p>
<p>This means that 87.42% of all samples were correctly classified.</p>
</section>
<section id="misclassification-analysis" class="level4">
<h4 class="anchored" data-anchor-id="misclassification-analysis"><strong>Misclassification Analysis</strong></h4>
<ul>
<li><p>The main sources of misclassification are <strong>66 false positives (FP)</strong> and <strong>76 false negatives (FN)</strong>.</p></li>
<li><p>False negatives (FN) indicate that some high-quality coffee samples were misclassified as low quality.</p></li>
<li><p>False positives (FP) suggest that some low-quality coffee samples were incorrectly classified as high quality.</p></li>
</ul>
</section>
<section id="conclusion-optimization-suggestions" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-optimization-suggestions"><strong>Conclusion &amp; Optimization Suggestions</strong></h4>
<ul>
<li><p>The model performs <strong>well overall</strong>, but <strong>misclassification still exists</strong>.</p></li>
<li><p><strong>Threshold tuning</strong> may help optimize the balance between FN and FP, depending on whether minimizing false positives or false negatives is more important for the application.</p></li>
</ul>
</section>
</section>
<section id="residual-analysis" class="level3">
<h3 class="anchored" data-anchor-id="residual-analysis"><strong>3.Residual Analysis</strong></h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Analysis_English_files/figure-html/residual_analysis-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Analysis_English_files/figure-html/residual_analysis-2.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<section id="residual-histogram" class="level4">
<h4 class="anchored" data-anchor-id="residual-histogram"><strong>（1）Residual Histogram</strong></h4>
<ul>
<li><p>Most residuals are concentrated around 0, following a normal distribution trend, though there is some skewness.</p></li>
<li><p>If the residuals exhibit a bell-shaped symmetric distribution, it indicates that the model’s errors are randomly distributed, which is a good sign.</p></li>
<li><p><strong>Conclusion:</strong></p>
<ul>
<li><p>Residuals appear well-concentrated, suggesting that the model has small prediction errors.</p></li>
<li><p>However, there is slight skewness, which may require further examination of variable selection in the model.</p></li>
</ul></li>
</ul>
</section>
<section id="qq-plot-analysis" class="level4">
<h4 class="anchored" data-anchor-id="qq-plot-analysis"><strong>（2）QQ Plot Analysis</strong></h4>
<ul>
<li><p><strong>Purpose:</strong><br>
The QQ plot is used to check whether the residuals follow a normal distribution.</p></li>
<li><p><strong>Observations:</strong></p>
<ul>
<li><p>The middle points mostly lie on the red reference line, indicating that the majority of residuals follow a normal distribution.</p></li>
<li><p>The tail points deviate significantly, suggesting a heavy-tailed distribution, meaning the data deviates from normality in the extreme values.</p></li>
</ul></li>
<li><p><strong>Conclusion:</strong></p>
<ul>
<li><p>Most residuals follow a normal distribution, indicating a good model fit.</p></li>
<li><p>However, the presence of heavy tails suggests possible outliers in the data or the need for a more complex modeling approach (e.g., incorporating nonlinear features).</p></li>
</ul></li>
</ul>
</section>
<section id="residuals-vs.-predicted-values" class="level4">
<h4 class="anchored" data-anchor-id="residuals-vs.-predicted-values"><strong>（3）Residuals vs.&nbsp;Predicted Values</strong></h4>
<ul>
<li><p><strong>Purpose:</strong><br>
This plot is used to check for heteroscedasticity, i.e., whether the error variance changes with predicted values.</p></li>
<li><p><strong>Observations:</strong></p>
<ul>
<li><p>The residuals are not completely randomly distributed but show two distinct clustering patterns, likely related to the binary classification nature of the problem.</p></li>
<li><p>This may indicate limitations in the linearity assumption of the model.</p></li>
</ul></li>
<li><p><strong>Possible Solutions:</strong></p>
<ul>
<li><p>Consider using nonlinear models (e.g., decision trees or random forests).</p></li>
<li><p>Introduce interaction terms or higher-order terms to improve the model fit.</p></li>
</ul></li>
<li><p><strong>Conclusion:</strong></p></li>
</ul>
<pre><code>The current model's residuals show some structured patterns, suggesting that further optimization of the model structure or variable selection may be necessary.</code></pre>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>